databases:
  - name: inventus
    plan: free
    databaseName: inventus
    user: inventus

services:
  - type: web
    name: inventus
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventus
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
